"""Extract the authors' code from their notebooks into an importable module.

Not a transcription. Every code cell of 00_Utils.ipynb,
00_MonotherapyUtils.ipynb and 00_CombinationtherapyUtils.ipynb is written out
byte for byte, in notebook order, into original/ddprism_original.py.

Only one kind of edit is applied, and every instance is logged: IPython line
magics (``%run``, ``%matplotlib``) are commented out, because they are not
Python and the notebooks use them where an import would go. Concatenating the
three files in order supplies what those %run lines were pulling in.

That ordering also papers over a latent bug in the originals: 00_Utils calls
scipy.stats.gaussian_kde but only does ``from scipy import stats``. It works
solely because 00_MonotherapyUtils later runs ``import scipy.stats``.

    python scripts/extract_original.py
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NOTEBOOKS = ["00_Utils.ipynb",
             "00_MonotherapyUtils.ipynb",
             "00_CombinationtherapyUtils.ipynb"]
OUT = ROOT / "original" / "ddprism_original.py"

HEADER = '''"""The authors' code, extracted verbatim from their notebooks.

DO NOT EDIT. Generated by scripts/extract_original.py from
https://github.com/GIST-CSBL/DD-PRiSM -- 00_Utils.ipynb,
00_MonotherapyUtils.ipynb and 00_CombinationtherapyUtils.ipynb, concatenated in
that order. Every line below is theirs except IPython magics, which are
commented out because they are not Python.

Licensed CC-BY-NC-SA-4.0 by the original authors. Cite:
Jin I, Lee S, Schmuhalek M, Nam H. DD-PRiSM: a deep learning framework for
decomposition and prediction of synergistic drug combinations.
Briefings in Bioinformatics 2025;26(1):bbae717.

Known quirks, left in place because they are the published behaviour:
  * CombinationTherapyModel builds efficacy_relu and viability_relu and never
    calls them, so predicted viability is unbounded and can go negative.
  * MonotherapyModel funnels four curve parameters through a 2-unit bottleneck.
  * test_/predict_ helpers call model.train() over the evaluation set before
    switching to eval(), which updates BatchNorm running statistics on test data.
  * `device` is a global these functions expect the caller to define.
"""

'''


def is_magic(line):
    stripped = line.lstrip()
    return stripped.startswith(("%", "!"))


def main():
    pieces, edits = [HEADER], []

    for name in NOTEBOOKS:
        path = ROOT / name
        if not path.exists():
            print(f"missing notebook: {path}")
            return 2

        notebook = json.loads(path.read_text(encoding="utf-8"))
        pieces.append(f"\n# {'=' * 74}\n# {name}\n# {'=' * 74}\n")

        for index, cell in enumerate(notebook["cells"]):
            if cell["cell_type"] != "code":
                continue
            source = cell["source"]
            source = "".join(source) if isinstance(source, list) else source
            if not source.strip():
                continue

            kept = []
            for number, line in enumerate(source.split("\n"), 1):
                if is_magic(line):
                    edits.append(f"{name} cell {index} line {number}: "
                                 f"commented out magic  {line.strip()}")
                    kept.append(f"# [extractor] {line}")
                else:
                    kept.append(line)
            pieces.append("\n".join(kept) + "\n")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    (OUT.parent / "__init__.py").write_text(
        '"""The authors\' unmodified code. See ddprism_original.py."""\n',
        encoding="utf-8")
    OUT.write_text("\n".join(pieces), encoding="utf-8")

    print(f"wrote {OUT.relative_to(ROOT)}")
    print(f"  lines: {len(OUT.read_text(encoding='utf-8').splitlines()):,}")
    print(f"  edits: {len(edits)}")
    for edit in edits:
        print(f"    {edit}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
